title: Кучеров Иван
logo: ![Logo](https://github.com/IvanAnalyst/IvanAnalyst/blob/main/My_Logo.png)
Email: unequivocally.ivan@gmail.com
Портфолио проектов: https://ivananalyst.github.io/My-projects 
Ожидаемая должность: Аналитик данных / Data Scientist
График работы: удаленная работа
show downloads: true
theme: jekyll-theme-minimal
